[package]
name = "simple-mev-bot"
version = "0.2.0"
edition = "2021"
description = "精简版MEV套利机器人 - 参考sui-mev架构设计"
license = "MIT"
repository = "https://github.com/SimpLe-L/arbitrage-bot"

[[bin]]
name = "simple-mev"
path = "src/main_simple.rs"

[dependencies]
# 异步运行时
tokio = { version = "1.0", features = ["full"] }

# 以太坊相关
ethers = { version = "2.0", features = ["ws", "rustls", "abigen"] }

# 错误处理
eyre = "0.6"
thiserror = "1.0"

# 命令行参数解析
clap = { version = "4.0", features = ["derive", "env"] }

# 日志
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# 序列化
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# 其他工具
hex = "0.4"

[dev-dependencies]
tokio-test = "0.4"

[features]
default = []
live-trading = []  # 启用真实交易功能

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

# 为了更快的编译时间
[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
