#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#avaxarbexecutor;
pub mod r#iaavev3pool;
pub mod r#ierc20;
pub mod r#iuniswapv2pair;
pub mod r#stdconstants;
